nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: false