nelmio_cors:
    defaults:
        allow_origin: ['https://frontend-neptun-o59eg.ondigitalocean.app', 'http://localhost:4200', '*']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-Order-List-Token', 'X-Order-List-Public']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT']
        expose_headers: ['Set-Cookie']
    paths:
        '^/api/':
            origin_regex: false
        '^/orders/':
            origin_regex: false
