nelmio_cors:
    defaults:
        allow_origin: ['https://frontend-neptun-o59eg.ondigitalocean.app']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        expose_headers: ['Set-Cookie']
    paths:
        '^/api/':
            origin_regex: false