controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_login:
    path: /login
    methods: [POST]
api_platform:
    resource: .
    type: api_platform
    prefix: /api